
version: 0.0
os: windows
files:
  - source: \
    destination: C:\inetpub\wwwroot
hooks:
  ApplicationStop:
    - location: scripts/stop.ps1
      timeout: 300
  BeforeInstall:
    - location: scripts/copy-files.ps1
      timeout: 300
  AfterInstall:
    - location: scripts/liquibaseupdate.ps1
      timeout:  300
  ApplicationStart:
    - location: scripts/start.ps1
      timeout: 300
