version: 0.0
os: windows
hooks:
  BeforeInstall:
    - location: scripts/stop.ps1
      timeout: 200
    - location: scripts/copy-files.ps1
      timeout: 200
    - location: scripts/liquibaseupdate.ps1
      timeout: 200
    - location: scripts/start.ps1
      timeout: 200
files:
  - source: /
    destination: C:\inetpub\wwwroot
