version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet restore
      - dotnet build
      - dotnet publish -c Release -o C:\codebuild\artifacts\publish_output
      - 'md C:\codebuild\artifacts\publish_output\scripts'
      - 'md C:\codebuild\artifacts\publish_output\db'
      - 'copy .\appspec.yml C:\codebuild\artifacts\publish_output'
      - 'copy .\liquibase.properties C:\codebuild\artifacts\publish_output'
      - 'PowerShell -Command "Copy-Item -Path .\scripts\* -Destination C:\codebuild\artifacts\publish_output\scripts -Recurse -Force"'
      - 'PowerShell -Command "Copy-Item -Path .\db\* -Destination C:\codebuild\artifacts\publish_output\db -Recurse -Force"'
      - dir C:\codebuild
      - dir C:\codebuild\artifacts\
      - dir C:\codebuild\artifacts\publish_output
artifacts:
  files:
    - 'publish_output/*'
    - 'appspec.yml'
    - 'liquibase.properties'
    - 'scripts/*'
    - 'db/*'    
  base-directory: 'C:\codebuild\artifacts\publish_output'

