version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
  build:
    commands:
      - dotnet restore
      - dotnet build
      - dotnet publish -c Release -o ./publish_output
artifacts:
  files:
    - '**/*'
  discard-paths: no

